# D02 NumPy 陣列進階操作
numpy 的各維度示意圖：
![1d](https://github.com/qaws5503/data_science/blob/main/picture/1d_axis.png?raw=true)
![2d](https://github.com/qaws5503/data_science/blob/main/picture/2D_axis.png?raw=true)
![3d](https://github.com/qaws5503/data_science/blob/main/picture/3D_axis.png?raw=true)

In [2]:
import numpy as np

#### 將上列陣列(array1)，轉成維度為(5X6)的 array，順序按列填充。(hint:order="F")

In [13]:
array1 = np.array(range(30))
reshape_array = array1.reshape(5,6,order="F")
print(array1.reshape(5,6))
print("\n 以下有加入 order:\n")
print(reshape_array)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]

 以下有加入 order:

[[ 0  5 10 15 20 25]
 [ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]]


#### 呈上題的 array，找出被 6 除餘 1 的數的索引
使用 where() 來尋找該位置，搜尋出來的第一個陣列是 axis=0 第二個陣列是 axis=1

In [14]:
np.where(reshape_array%6 == 1)

(array([0, 1, 2, 3, 4]), array([5, 0, 1, 2, 3]))