# D07 NumPy 的矩陣函式與線性代數應用

### 基本函式

* 點積：np.dot(a, b)、二維時也可以使用 @ 或 np.matmul(a, b)
* 內積：np.inner(a, b)
* 外積：np.outer(a, b)
* trace：np.trace(a)
* 行列式：np.linalg.det(A)
* 反矩陣：np.linalg.inv(A)
* 轉置：np.transpose()
* 特徵值：w,v = np.linalg.eig(a)，w:eigenvalues, v:eigenvectors
* solve：np.linalg.solve(a, b)

### 問題

array1 = np.array([[10, 8], [3, 5]])

1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
2. 運用上列array計算特徵值、特徵向量?
3. 運用上列array計算SVD?

In [3]:
import numpy as np
array1 = np.array([[10, 8], [3, 5]])
inv = np.linalg.inv(array1)
mul = array1 @ inv
print("反矩陣為：")
print(inv)
print("反矩陣乘上原矩陣：")
print(mul)
print("單位矩陣為：")
print(np.identity(2))

反矩陣為：
[[ 0.19230769 -0.30769231]
 [-0.11538462  0.38461538]]
反矩陣乘上原矩陣：
[[1. 0.]
 [0. 1.]]
單位矩陣為：
[[1. 0.]
 [0. 1.]]


In [4]:
w, v = np.linalg.eig(array1)
print("eigenvalues:")
print(w)
print("eigenvectors:")
print(v)

eigenvalues:
[13.  2.]
eigenvectors:
[[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [7]:
u, s, vh = np.linalg.svd(array1)
print(u)
print("\n")
print(s)
print("\n")
print(vh)

[[-0.91663818 -0.39971796]
 [-0.39971796  0.91663818]]


[13.94721714  1.86417116]


[[-0.74319741 -0.6690722 ]
 [-0.6690722   0.74319741]]
