# D01 NumPy 套件基本操作

In [1]:
import numpy as np

## 生成一個等差數列，首數為 0，尾數為 20，公差為 1 的數列。

In [11]:
num = np.arange(21)
num

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

## 承上題，將以上數列取出偶數。

In [12]:
even = []
for i in range(len(num)):
    if num[i]%2 == 0:
        even.append(num[i])

even = np.array(even)
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

## 承 1 題，將數列取出 3 的倍數。

In [14]:
new_num = []
for i in range(len(num)):
    if num[i]!=0 and num[i]%3 == 0:
        new_num.append(num[i])

new_num = np.array(new_num)
new_num

array([ 3,  6,  9, 12, 15, 18])