# D11 pandas 類別資料與缺失值處理

### 編碼：

#### LabelEncoder

```
from sklearn.preprocessing import LabelEncoder
>>> le = preprocessing.LabelEncoder()
>>> le.fit([1, 2, 2, 6])
LabelEncoder()
>>> le.classes_
array([1, 2, 6])
>>> le.transform([1, 1, 2, 6])
array([0, 0, 1, 2]...)
>>> le.inverse_transform([0, 0, 1, 2])
array([1, 1, 2, 6])
```

#### One-hot encoding

```
import pandas as pd
pd.get_dummies(df[['colors']])
```

### 問題：

將以下問卷資料的職業(Profession)欄位缺失值填入字串'others'，更進一步將字串做編碼。 此時用什麼方式做編碼比較適合?為什麼?

In [2]:
import pandas as pd
q_df = pd.DataFrame([['male', 'teacher'], ['male', 'engineer'], ['female', None], ['female', 'engineer']],columns=['Sex','Profession'])
q_df

Sex Profession
0    male    teacher
1    male   engineer
2  female       None
3  female   engineer

In [4]:
q_df = q_df.fillna('others')
q_df

Sex Profession
0    male    teacher
1    male   engineer
2  female     others
3  female   engineer

In [8]:
# 適合使用 one-hot encoding，因為職業欄位沒有大小排序的問題

q_df = pd.concat([q_df, pd.get_dummies(q_df['Profession'])], axis=1)
q_df

Sex Profession  engineer  others  teacher
0    male    teacher         0       0        1
1    male   engineer         1       0        0
2  female     others         0       1        0
3  female   engineer         1       0        0